<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockEnumerable" Id="{91f90a77-a44e-4ee3-8f71-353f56d1b688}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MockEnumerable IMPLEMENTS I_Enumerable
VAR
	enumerator : MockForwardEnumerator(FALSE,FALSE,FALSE,FALSE);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetEnumerator" Id="{3c2bf8e0-a457-4dd0-a532-1814fdd460da}">
      <Declaration><![CDATA[METHOD PUBLIC GetEnumerator : I_ForwardEnumerator]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetEnumerator := enumerator;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>